name: better_components
description: "A collection of better components"
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  utils:
    git:
      url: https://github.com/Order-of-Runes/utils.git
      ref: 0.0.6

dev_dependencies:
  very_good_analysis: ^7.0.0